// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikdicplcbambhspuhnjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZGljcGxjYmFtYmhzcHVobmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODE5NDksImV4cCI6MjA1OTk1Nzk0OX0.OVxcWQUN3levax3_F19UTbWEJ3cvY5Y8koai8FsY82k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);